### ISSUE TITLE
Support translation language arg

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/youtube-vtt#2]
https://github.com/benwiley4000/youtube-vtt/issues/1#issuecomment-702850691 cc @dirxiang

**Comment by benwiley4000** [comment]
@dirxiang please try the latest updated version: https://github.com/benwiley4000/youtube-vtt

You can use for example:
```js
saveVttFiles({ translationLanguageCode: 'zh-Hans' });
```

Please let me know if this works well for you!

**Comment by dirxiang** [comment]
Yes it worked perfectly!  This is awesome!  Thank you!!!

**Comment by benwiley4000** [comment]
Great!
