### ISSUE TITLE
Unexpected JSON token error message

### ISSUE THREAD

**Issue by aamassoud** [benwiley4000/youtube-vtt#4]
Hello, @benwiley4000,

Following the simple usage and command line usage instructions in your README, I am still unable to successfully download a closed caption file. In both the Chrome JavaScript console and my CLI, I am receiving the same error:

**Unexpected token u in JSON at position 0**

As an example, this is the YouTube video I was working with, although I got the same error with other videos: [A disfigured Randy Orton sends fiery message to The Fiend: Raw, Jan. 18, 2021](https://www.youtube.com/watch?v=3PWCCJNhi-4)

I am using Windows Terminal and have installed Node.js v14.15.4. Could I be missing other necessary packages, or is there another issue?

Thank you

**Comment by SLG** [comment]
@benwiley4000 I ran into the same problem and found a fix.
However, I cannot push the fix to a new branch to create a PR. Can you allow me?

**Comment by benwiley4000** [comment]
Hi sorry for the delayed response. You need to fork the repository first, then create a branch on your fork, and GitHub will make it easy to open a PR from your fork branch to my repo. Let me know if you have any other questions!

**Comment by SLG** [comment]
Check, found it! Created a PR.

**Comment by parthu34** [comment]
> Hello, @benwiley4000,
> 
> Following the simple usage and command line usage instructions in your README, I am still unable to successfully download a closed caption file. In both the Chrome JavaScript console and my CLI, I am receiving the same error:
> 
> **Unexpected token u in JSON at position 0**
> 
> As an example, this is the YouTube video I was working with, although I got the same error with other videos: [A disfigured Randy Orton sends fiery message to The Fiend: Raw, Jan. 18, 2021](https://www.youtube.com/watch?v=3PWCCJNhi-4)
> 
> I am using Windows Terminal and have installed Node.js v14.15.4. Could I be missing other necessary packages, or is there another issue?
> 
> Thank you

Same issue with me.

**Comment by gquach** [comment]
I can confirm that @SLG's PR works well and fixes the issue for me.
https://github.com/benwiley4000/youtube-vtt/pull/5

**Comment by benwiley4000** [comment]
v0.2.0 released with this fix. Very sorry about the delay.
